title: Jean MANOURY
description: Portfolio technique
site_title: '@cieldeb - Jean MANOURY'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: cieldeb
#blog_url: https://www.nagekar.com
email: jean.manoury@outlook.fr

# absolute or relative
profile_picture: assets/images/pp.jpg
